spring.application.name=UsuariosSecurity
server.port=8050
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=ENUCOM13
spring.datasource.password=enucom
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format-sql=true